# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.cluster_members_member_id.delete.operation import ApiForDelete
from nethsm.client.paths.cluster_members_member_id.put.operation import ApiForPut


class ClusterMembersMemberID(
    ApiForDelete,
    ApiForPut,
):
    pass
