# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.cluster_force_new.post.operation import ApiForPost


class ClusterForceNew(
    ApiForPost,
):
    pass
