# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.cluster_members.get.operation import ApiForGet
from nethsm.client.paths.cluster_members.post.operation import ApiForPost


class ClusterMembers(
    ApiForGet,
    ApiForPost,
):
    pass
