# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.cluster_members_member_id_promote.post.operation import ApiForPost


class ClusterMembersMemberIDPromote(
    ApiForPost,
):
    pass
