# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.config_ntp.get.operation import ApiForGet
from nethsm.client.paths.config_ntp.put.operation import ApiForPut


class ConfigNtp(
    ApiForGet,
    ApiForPut,
):
    pass
