# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.config_unlock_passphrase.put.operation import ApiForPut


class ConfigUnlockPassphrase(
    ApiForPut,
):
    pass
