# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.config_tls_cluster_ca_pem.get.operation import ApiForGet
from nethsm.client.paths.config_tls_cluster_ca_pem.put.operation import ApiForPut


class ConfigTlsClusterCaPem(
    ApiForGet,
    ApiForPut,
):
    pass
