# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.config_tls_public_pem.get.operation import ApiForGet


class ConfigTlsPublicPem(
    ApiForGet,
):
    pass
