# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.health_diagnose.get.operation import ApiForGet


class HealthDiagnose(
    ApiForGet,
):
    pass
