# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.keys_key_id_label.delete.operation import ApiForDelete
from nethsm.client.paths.keys_key_id_label.put.operation import ApiForPut


class KeysKeyIDLabel(
    ApiForDelete,
    ApiForPut,
):
    pass
