# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.keys_key_prefix.get.operation import ApiForGet


class KeysKeyPrefix(
    ApiForGet,
):
    pass
