# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.keys_key_id_move.post.operation import ApiForPost


class KeysKeyIDMove(
    ApiForPost,
):
    pass
