# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.namespaces_namespace_id.delete.operation import ApiForDelete
from nethsm.client.paths.namespaces_namespace_id.put.operation import ApiForPut


class NamespacesNamespaceID(
    ApiForDelete,
    ApiForPut,
):
    pass
