# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.namespaces.get.operation import ApiForGet


class Namespaces(
    ApiForGet,
):
    pass
