# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.users_user_id_namespace.get.operation import ApiForGet


class UsersUserIDNamespace(
    ApiForGet,
):
    pass
