# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.users_user_id.delete.operation import ApiForDelete
from nethsm.client.paths.users_user_id.get.operation import ApiForGet
from nethsm.client.paths.users_user_id.post.operation import ApiForPost
from nethsm.client.paths.users_user_id.put.operation import ApiForPut


class UsersUserID(
    ApiForDelete,
    ApiForGet,
    ApiForPost,
    ApiForPut,
):
    pass
