# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from nethsm.client.paths.users_user_id_tags_tag.delete.operation import ApiForDelete
from nethsm.client.paths.users_user_id_tags_tag.put.operation import ApiForPut


class UsersUserIDTagsTag(
    ApiForDelete,
    ApiForPut,
):
    pass
