# coding: utf-8

"""
    NetHSM
    All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.   # noqa: E501
    The version of the OpenAPI document: v1
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from __future__ import annotations
from nethsm.client.shared_imports.schema_imports import *  # pyright: ignore [reportWildcardImportFromLibrary]


from nethsm.client.components.schema import cluster_member


class ClusterMemberListTuple(
    typing.Tuple[
        cluster_member.ClusterMemberDict,
        ...
    ]
):

    def __new__(cls, arg: typing.Union[ClusterMemberListTupleInput, ClusterMemberListTuple], configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None):
        return ClusterMemberList.validate(arg, configuration=configuration)
ClusterMemberListTupleInput = typing.Union[
    typing.List[
        typing.Union[
            cluster_member.ClusterMemberDictInput,
            cluster_member.ClusterMemberDict,
        ],
    ],
    typing.Tuple[
        typing.Union[
            cluster_member.ClusterMemberDictInput,
            cluster_member.ClusterMemberDict,
        ],
        ...
    ]
]


@dataclasses.dataclass(frozen=True)
class ClusterMemberList(
    schemas.Schema[schemas.immutabledict, ClusterMemberListTuple]
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator.
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    types: typing.FrozenSet[typing.Type] = frozenset({tuple})
    items: typing.Type[cluster_member.ClusterMember] = dataclasses.field(default_factory=lambda: cluster_member.ClusterMember) # type: ignore
    type_to_output_cls: typing.Mapping[
        typing.Type,
        typing.Type
    ] = dataclasses.field(
        default_factory=lambda: {
            tuple: ClusterMemberListTuple
        }
    )

    @classmethod
    def validate(
        cls,
        arg: typing.Union[
            ClusterMemberListTupleInput,
            ClusterMemberListTuple,
        ],
        configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None
    ) -> ClusterMemberListTuple:
        return super().validate_base(
            arg,
            configuration=configuration,
        )
