# coding: utf-8

"""
    NetHSM
    All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.   # noqa: E501
    The version of the OpenAPI document: v1
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from __future__ import annotations
from nethsm.client.shared_imports.schema_imports import *  # pyright: ignore [reportWildcardImportFromLibrary]

Cidr: typing_extensions.TypeAlias = schemas.StrSchema

from nethsm.client.components.schema import ipv6_gateway
Properties = typing.TypedDict(
    'Properties',
    {
        "cidr": typing.Type[Cidr],
        "gateway": typing.Type[ipv6_gateway.Ipv6Gateway],
    }
)


class Ipv6ConfigDict(schemas.immutabledict[str, schemas.OUTPUT_BASE_TYPES]):

    __required_keys__: typing.FrozenSet[str] = frozenset({
        "cidr",
        "gateway",
    })
    __optional_keys__: typing.FrozenSet[str] = frozenset({
    })
    
    def __new__(
        cls,
        *,
        cidr: str,
        gateway: typing.Union[
            None,
            str,
        ],
        configuration_: typing.Optional[schema_configuration.SchemaConfiguration] = None,
        **kwargs: schemas.INPUT_TYPES_ALL,
    ):
        arg_: typing.Dict[str, typing.Any] = {
            "cidr": cidr,
            "gateway": gateway,
        }
        arg_.update(kwargs)
        used_arg_ = typing.cast(Ipv6ConfigDictInput, arg_)
        return Ipv6Config.validate(used_arg_, configuration=configuration_)
    
    @staticmethod
    def from_dict_(
        arg: typing.Union[
            Ipv6ConfigDictInput,
            Ipv6ConfigDict
        ],
        configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None
    ) -> Ipv6ConfigDict:
        return Ipv6Config.validate(arg, configuration=configuration)
    
    @property
    def cidr(self) -> str:
        return typing.cast(
            str,
            self.__getitem__("cidr")
        )
    
    @property
    def gateway(self) -> typing.Union[
        None,
        str,
    ]:
        return typing.cast(
            typing.Union[
                None,
                str,
            ],
            self.__getitem__("gateway")
        )
    
    def get_additional_property_(self, name: str) -> typing.Union[schemas.OUTPUT_BASE_TYPES, schemas.Unset]:
        schemas.raise_if_key_known(name, self.__required_keys__, self.__optional_keys__)
        return self.get(name, schemas.unset)
Ipv6ConfigDictInput = typing.Mapping[str, schemas.INPUT_TYPES_ALL]


@dataclasses.dataclass(frozen=True)
class Ipv6Config(
    schemas.Schema[Ipv6ConfigDict, tuple]
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator.
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    types: typing.FrozenSet[typing.Type] = frozenset({schemas.immutabledict})
    required: typing.FrozenSet[str] = frozenset({
        "cidr",
        "gateway",
    })
    properties: Properties = dataclasses.field(default_factory=lambda: schemas.typed_dict_to_instance(Properties)) # type: ignore
    type_to_output_cls: typing.Mapping[
        typing.Type,
        typing.Type
    ] = dataclasses.field(
        default_factory=lambda: {
            schemas.immutabledict: Ipv6ConfigDict
        }
    )

    @classmethod
    def validate(
        cls,
        arg: typing.Union[
            Ipv6ConfigDictInput,
            Ipv6ConfigDict,
        ],
        configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None
    ) -> Ipv6ConfigDict:
        return super().validate_base(
            arg,
            configuration=configuration,
        )

