# coding: utf-8

"""
    NetHSM
    All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.   # noqa: E501
    The version of the OpenAPI document: v1
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from __future__ import annotations
from nethsm.client.shared_imports.schema_imports import *  # pyright: ignore [reportWildcardImportFromLibrary]



@dataclasses.dataclass(frozen=True)
class Length(
    schemas.AnyTypeSchema[schemas.immutabledict[str, schemas.OUTPUT_BASE_TYPES], typing.Tuple[schemas.OUTPUT_BASE_TYPES, ...]],
):
    # any type
    inclusive_maximum: typing.Union[int, float] = 32
    inclusive_minimum: typing.Union[int, float] = 0

Properties = typing.TypedDict(
    'Properties',
    {
        "length": typing.Type[Length],
    }
)
KeyLabelDictInput = typing.Mapping[str, schemas.INPUT_TYPES_ALL]
KeyLabel: typing_extensions.TypeAlias = schemas.StrSchema
