# coding: utf-8

"""
    NetHSM
    All endpoints expect exactly the specified JSON. Additional properties will cause a Bad Request Error (400). All HTTP errors contain a JSON structure with an explanation of type string. All [base64](https://tools.ietf.org/html/rfc4648#section-4) encoded values are Big Endian.   # noqa: E501
    The version of the OpenAPI document: v1
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from __future__ import annotations
from nethsm.client.shared_imports.schema_imports import *  # pyright: ignore [reportWildcardImportFromLibrary]

IpAddress: typing_extensions.TypeAlias = schemas.StrSchema
Netmask: typing_extensions.TypeAlias = schemas.StrSchema
Gateway: typing_extensions.TypeAlias = schemas.StrSchema

from nethsm.client.components.schema import ipv6_config
Properties = typing.TypedDict(
    'Properties',
    {
        "ipAddress": typing.Type[IpAddress],
        "netmask": typing.Type[Netmask],
        "gateway": typing.Type[Gateway],
        "ipv6": typing.Type[ipv6_config.Ipv6Config],
    }
)


class NetworkConfigInputDict(schemas.immutabledict[str, schemas.OUTPUT_BASE_TYPES]):

    __required_keys__: typing.FrozenSet[str] = frozenset({
        "ipAddress",
        "netmask",
    })
    __optional_keys__: typing.FrozenSet[str] = frozenset({
        "gateway",
        "ipv6",
    })
    
    def __new__(
        cls,
        *,
        ipAddress: str,
        netmask: str,
        gateway: typing.Union[
            str,
            schemas.Unset
        ] = schemas.unset,
        ipv6: typing.Union[
            ipv6_config.Ipv6ConfigDictInput,
            ipv6_config.Ipv6ConfigDict,
            schemas.Unset
        ] = schemas.unset,
        configuration_: typing.Optional[schema_configuration.SchemaConfiguration] = None,
        **kwargs: schemas.INPUT_TYPES_ALL,
    ):
        arg_: typing.Dict[str, typing.Any] = {
            "ipAddress": ipAddress,
            "netmask": netmask,
        }
        for key_, val in (
            ("gateway", gateway),
            ("ipv6", ipv6),
        ):
            if isinstance(val, schemas.Unset):
                continue
            arg_[key_] = val
        arg_.update(kwargs)
        used_arg_ = typing.cast(NetworkConfigInputDictInput, arg_)
        return NetworkConfigInput.validate(used_arg_, configuration=configuration_)
    
    @staticmethod
    def from_dict_(
        arg: typing.Union[
            NetworkConfigInputDictInput,
            NetworkConfigInputDict
        ],
        configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None
    ) -> NetworkConfigInputDict:
        return NetworkConfigInput.validate(arg, configuration=configuration)
    
    @property
    def ipAddress(self) -> str:
        return typing.cast(
            str,
            self.__getitem__("ipAddress")
        )
    
    @property
    def netmask(self) -> str:
        return typing.cast(
            str,
            self.__getitem__("netmask")
        )
    
    @property
    def gateway(self) -> typing.Union[str, schemas.Unset]:
        val = self.get("gateway", schemas.unset)
        if isinstance(val, schemas.Unset):
            return val
        return typing.cast(
            str,
            val
        )
    
    @property
    def ipv6(self) -> typing.Union[ipv6_config.Ipv6ConfigDict, schemas.Unset]:
        val = self.get("ipv6", schemas.unset)
        if isinstance(val, schemas.Unset):
            return val
        return typing.cast(
            ipv6_config.Ipv6ConfigDict,
            val
        )
    
    def get_additional_property_(self, name: str) -> typing.Union[schemas.OUTPUT_BASE_TYPES, schemas.Unset]:
        schemas.raise_if_key_known(name, self.__required_keys__, self.__optional_keys__)
        return self.get(name, schemas.unset)
NetworkConfigInputDictInput = typing.Mapping[str, schemas.INPUT_TYPES_ALL]


@dataclasses.dataclass(frozen=True)
class NetworkConfigInput(
    schemas.Schema[NetworkConfigInputDict, tuple]
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator.
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    types: typing.FrozenSet[typing.Type] = frozenset({schemas.immutabledict})
    required: typing.FrozenSet[str] = frozenset({
        "ipAddress",
        "netmask",
    })
    properties: Properties = dataclasses.field(default_factory=lambda: schemas.typed_dict_to_instance(Properties)) # type: ignore
    type_to_output_cls: typing.Mapping[
        typing.Type,
        typing.Type
    ] = dataclasses.field(
        default_factory=lambda: {
            schemas.immutabledict: NetworkConfigInputDict
        }
    )

    @classmethod
    def validate(
        cls,
        arg: typing.Union[
            NetworkConfigInputDictInput,
            NetworkConfigInputDict,
        ],
        configuration: typing.Optional[schema_configuration.SchemaConfiguration] = None
    ) -> NetworkConfigInputDict:
        return super().validate_base(
            arg,
            configuration=configuration,
        )

